name: 'Eleos Charity'
description: 'A suite of Commerce recipes for Drupal Charity sites'
type: 'Commerce'
recipes:
  - recipes/contrib/eleos_charity/eleos_charity_commerce_base
  - recipes/contrib/eleos_charity/eleos_charity_shop_category
  - recipes/contrib/eleos_charity/eleos_charity_basic_product
