name: 'Eleos Charity - Commerce Base'
description: 'Initial configuration for Commerce'
type: 'Commerce'
install:
  - commerce
  - commerce_log
  - commerce_number_pattern
  - commerce_order
  - commerce_store
  - commerce_price
  - commerce_cart
  - commerce_product
config:
  import:
    commerce: '*'
    commerce_log: '*'
    commerce_number_pattern: '*'
    commerce_order: '*'
    commerce_store: '*'
    commerce_price: '*'
    commerce_cart: '*'
    commerce_product: '*'
