name: 'Eleos Charity - Shop Category'
description: 'A category for Eleos Charity shops'
type: 'Commerce'
recipes:
  - core/recipes/image_media_type
  - eleos_charity_commerce_base
install:
  - media
  - media_library
  - taxonomy
