name: 'Eleos Charity - Shop Category'
description: 'A category for Eleos Charity shops'
type: 'Commerce'
recipes:
  - core/recipes/image_media_type
  - eleos-charity-commerce-base
install:
  - taxonomy
  - media
  - media_library
